/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import org.junit.Test;
import static org.junit.Assert.*;
import com.revature.models.Person;

public class AppTest {
    @Test public void appHasAGreeting() {
        Person classUnderTest = new Person();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
